import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-r from-cyan-500 to-blue-500`}
      >
        <div className="flex h-screen">
          <div className="m-auto mt-8 max-w-xl items-center justify-center rounded bg-white p-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
